### ISSUE TITLE
Mauvais affichage des noms de villes

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/sirene_as_api#72]
Par exemple, pour https://entreprise.data.gouv.fr/entreprise/43949920300016, on affiche “OLORON SAINTE MARIE”, on devrait afficher “OLORON-SAINTE-MARIE” (ou mieux “Oloron-Sainte-Marie”)

**Comment by Samuelfaure** [comment]
Je ne suis pas sûr qu'il soit judicieux de changer les retours de la base de donnée sur l'API, je vais ouvrir la suggestion sur le front cependant
